### ISSUE TITLE
Release Jar

### ISSUE THREAD

**Issue by 1337god** [Geolykt/dynamic-marketplace#1]
Will you be providing a release jar on https://geolykt.de/products/bukkitplugins.html or here?

**Comment by Geolykt** [comment]
yes, I will, but not yet as I'm planning to develop some features that would require the configuration to be changed (in a compatible manner - however I don't quite like that), which will have an issue when the product is released to the open world. It will be something that will be added one day soon (TM), but there is no real ETA.
