### ISSUE TITLE
Getting money from item in offhand hand

### ISSUE THREAD

**Issue by 1337god** [Geolykt/dynamic-marketplace#2]
When they use /sellall and there's an item on the off-set hand they don't lose it and get money from it.
From: https://github.com/erobertson-misc/dynamic-marketplace/issues/4

**Comment by Geolykt** [comment]
This is a near full recode of the original plugin which results in this probably not being an issue, but I'll check it anyways just to be sure, so thanks

**Comment by Geolykt** [comment]
Looked at it and this bug doesn't occour in that way, but it's still bugged in that everything is cleared, but only the items in offhand are actually sold

**Comment by Geolykt** [comment]
This bug actually does not happen and the bug I found earlier was unrelated (apart that it also is reproducible with sellall)
